In [21]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.qda import QDA
from sklearn.lda import LDA

//anaconda/lib/python3.5/site-packages/sklearn/lda.py:6: DeprecationWarning: lda.LDA has been moved to discriminant_analysis.LinearDiscriminantAnalysis in 0.17 and will be removed in 0.19
  "in 0.17 and will be removed in 0.19", DeprecationWarning)


In [13]:
train_file = "../data_set_generator/train.csv"
dev_file = "../data_set_generator/dev.csv"
test_file = "../data_set_generator/test.csv"

# Section 1: Data with all composers

In [14]:
train_data = pd.read_csv(train_file)
dev_data = pd.read_csv(dev_file)
labels = ["bach", "beethoven", "brahms", "chopin", "debussy", "handel", "haydn", "liszt", "mozart", "vivaldi"]

In [15]:
train_y = train_data[['y']]
train_X = train_data.drop(['y', 'Note_Density_per_Quarter_Note_Variability'], axis=1)
dev_y = dev_data[['y']]
dev_X = dev_data.drop(['y', 'Note_Density_per_Quarter_Note_Variability'], axis=1)

# Softmax Regression

In [8]:
# Modeling
clf = LogisticRegression(multi_class='multinomial', solver='lbfgs', penalty='l2').fit(train_X, train_y)

//anaconda/lib/python3.5/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [9]:
# Training data
y_pred = clf.predict(train_X)
confusion_m = confusion_matrix(train_y, y_pred)
training_accuracy = clf.score(train_X, train_y)
print(training_accuracy)
print(confusion_m)

0.6650069156293222
[[827  20   0   2   0   3   0   0   0   0]
 [ 58 326  18  26   0  25   0   3   0   0]
 [  1  58  18  45   1  40   7   0   0   0]
 [  0  12  16 139   2  38   2   1   0   1]
 [  0   1   5  41   9  50  15   7   1   0]
 [  0   1   5   4   1 256  49   1  71  29]
 [  0   1   7  11   0  63  87   4  88   4]
 [  0   0   4  14   0  15   9  77  64   4]
 [  0   0   5   0   0  17  12  24 609  66]
 [  0   0   0   0   0   0   0   0 139  56]]


In [11]:
# Dev data
y_pred = clf.predict(dev_X)
confusion_m = confusion_matrix(dev_y, y_pred)
dev_accuracy = clf.score(dev_X, dev_y)
print(dev_accuracy)
print(confusion_m)

0.6464730290456432
[[283   6   0   0   0   1   0   1   0   0]
 [ 24 108   9   8   1  11   0   1   0   0]
 [  0  20   8  17   1  12   2   1   0   0]
 [  0   8   2  38   0   9   1   0   0   0]
 [  0   0   1  17   0  16   6   2   0   0]
 [  0   0   3   2   1  51  17   3  23  11]
 [  0   0   0   2   0  16  20   0  35   3]
 [  0   0   2   3   2   5   5  24  29   0]
 [  0   0   2   0   0   7   3   3 228  21]
 [  0   0   0   0   0   0   0   0  51  19]]


# SVM, C =1

In [141]:
clf = SVC(gamma = 'auto', kernel='rbf', C=1)
clf.fit(train_X, train_y)

//anaconda/lib/python3.5/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [142]:
# Training data
y_pred = clf.predict(train_X)
confusion_m = confusion_matrix(train_y, y_pred)
training_accuracy = clf.score(train_X, train_y)
print(training_accuracy)
print(confusion_m)

1.0
[[852   0   0   0   0   0   0   0   0   0]
 [  0 456   0   0   0   0   0   0   0   0]
 [  0   0 170   0   0   0   0   0   0   0]
 [  0   0   0 211   0   0   0   0   0   0]
 [  0   0   0   0 129   0   0   0   0   0]
 [  0   0   0   0   0 417   0   0   0   0]
 [  0   0   0   0   0   0 265   0   0   0]
 [  0   0   0   0   0   0   0 187   0   0]
 [  0   0   0   0   0   0   0   0 733   0]
 [  0   0   0   0   0   0   0   0   0 195]]


In [143]:
# Dev data
y_pred = clf.predict(dev_X)
confusion_m = confusion_matrix(dev_y, y_pred)
dev_accuracy = clf.score(dev_X, dev_y)
print(dev_accuracy)
print(confusion_m)

0.24564315352697094
[[291   0   0   0   0   0   0   0   0   0]
 [162   0   0   0   0   0   0   0   0   0]
 [ 61   0   0   0   0   0   0   0   0   0]
 [ 58   0   0   0   0   0   0   0   0   0]
 [ 42   0   0   0   0   0   0   0   0   0]
 [111   0   0   0   0   0   0   0   0   0]
 [ 75   0   0   0   0   0   1   0   0   0]
 [ 70   0   0   0   0   0   0   0   0   0]
 [260   0   0   0   0   0   0   0   4   0]
 [ 70   0   0   0   0   0   0   0   0   0]]


# SVM, C = .45

In [144]:
clf = SVC(gamma = 'auto', kernel='rbf', C=.45)
clf.fit(train_X, train_y)

//anaconda/lib/python3.5/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=0.45, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [145]:
# Training data
y_pred = clf.predict(train_X)
confusion_m = confusion_matrix(train_y, y_pred)
training_accuracy = clf.score(train_X, train_y)
print(training_accuracy)
print(confusion_m)

0.23623789764868602
[[852   0   0   0   0   0   0   0   0   0]
 [454   2   0   0   0   0   0   0   0   0]
 [170   0   0   0   0   0   0   0   0   0]
 [211   0   0   0   0   0   0   0   0   0]
 [129   0   0   0   0   0   0   0   0   0]
 [417   0   0   0   0   0   0   0   0   0]
 [265   0   0   0   0   0   0   0   0   0]
 [187   0   0   0   0   0   0   0   0   0]
 [733   0   0   0   0   0   0   0   0   0]
 [195   0   0   0   0   0   0   0   0   0]]


In [146]:
# Dev data
y_pred = clf.predict(dev_X)
confusion_m = confusion_matrix(dev_y, y_pred)
dev_accuracy = clf.score(dev_X, dev_y)
print(dev_accuracy)
print(confusion_m)

0.24149377593360996
[[291   0   0   0   0   0   0   0   0   0]
 [162   0   0   0   0   0   0   0   0   0]
 [ 61   0   0   0   0   0   0   0   0   0]
 [ 58   0   0   0   0   0   0   0   0   0]
 [ 42   0   0   0   0   0   0   0   0   0]
 [111   0   0   0   0   0   0   0   0   0]
 [ 76   0   0   0   0   0   0   0   0   0]
 [ 70   0   0   0   0   0   0   0   0   0]
 [264   0   0   0   0   0   0   0   0   0]
 [ 70   0   0   0   0   0   0   0   0   0]]


# SVM, Kernel = Linear

In [147]:
clf = SVC(gamma = 'auto', kernel='linear', C=1)
clf.fit(train_X, train_y)

//anaconda/lib/python3.5/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [148]:
# Training data
y_pred = clf.predict(train_X)
confusion_m = confusion_matrix(train_y, y_pred)
training_accuracy = clf.score(train_X, train_y)
print(training_accuracy)
print(confusion_m)

1.0
[[852   0   0   0   0   0   0   0   0   0]
 [  0 456   0   0   0   0   0   0   0   0]
 [  0   0 170   0   0   0   0   0   0   0]
 [  0   0   0 211   0   0   0   0   0   0]
 [  0   0   0   0 129   0   0   0   0   0]
 [  0   0   0   0   0 417   0   0   0   0]
 [  0   0   0   0   0   0 265   0   0   0]
 [  0   0   0   0   0   0   0 187   0   0]
 [  0   0   0   0   0   0   0   0 733   0]
 [  0   0   0   0   0   0   0   0   0 195]]


In [149]:
# Dev data
y_pred = clf.predict(dev_X)
confusion_m = confusion_matrix(dev_y, y_pred)
dev_accuracy = clf.score(dev_X, dev_y)
print(dev_accuracy)
print(confusion_m)

0.9900414937759336
[[291   0   0   0   0   0   0   0   0   0]
 [  0 162   0   0   0   0   0   0   0   0]
 [  0   1  57   3   0   0   0   0   0   0]
 [  0   0   2  53   3   0   0   0   0   0]
 [  0   0   0   0  42   0   0   0   0   0]
 [  0   0   0   0   0 110   1   0   0   0]
 [  0   0   0   0   0   0  76   0   0   0]
 [  0   0   0   0   0   0   0  70   0   0]
 [  0   0   0   0   0   0   0   1 262   1]
 [  0   0   0   0   0   0   0   0   0  70]]


# LDA

In [22]:
clf = LDA()
clf.fit(train_X, train_y)

//anaconda/lib/python3.5/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
//anaconda/lib/python3.5/site-packages/sklearn/discriminant_analysis.py:387: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


LDA(n_components=None, priors=None, shrinkage=None, solver='svd',
  store_covariance=False, tol=0.0001)

In [23]:
# Training data
y_pred = clf.predict(train_X)
confusion_m = confusion_matrix(train_y, y_pred)
training_accuracy = clf.score(train_X, train_y)
print(training_accuracy)
print(confusion_m)

0.9964038727524205
[[851   1   0   0   0   0   0   0   0   0]
 [  0 456   0   0   0   0   0   0   0   0]
 [  0   4 164   1   0   1   0   0   0   0]
 [  0   0   0 211   0   0   0   0   0   0]
 [  0   0   0   0 129   0   0   0   0   0]
 [  0   0   0   0   0 416   1   0   0   0]
 [  0   0   0   0   0   0 265   0   0   0]
 [  0   0   0   0   0   0   1 184   2   0]
 [  0   0   0   0   0   0   0   0 733   0]
 [  0   0   0   0   0   0   0   0   2 193]]


In [24]:
# Dev data
y_pred = clf.predict(dev_X)
confusion_m = confusion_matrix(dev_y, y_pred)
dev_accuracy = clf.score(dev_X, dev_y)
print(dev_accuracy)
print(confusion_m)

0.9004149377593361
[[270   7   7   1   3   0   1   0   2   0]
 [  3 150   6   2   1   0   0   0   0   0]
 [  0  14  40   5   2   0   0   0   0   0]
 [  0   3   9  42   0   2   0   2   0   0]
 [  0   0   4   0  35   2   1   0   0   0]
 [  0   0   4   0   0 102   2   0   1   2]
 [  0   0   0   0   1   0  74   0   1   0]
 [  0   0   2   1   4   2   1  57   3   0]
 [  0   1   5   0   0   0   4   3 250   1]
 [  0   0   0   0   0   0   1   1   3  65]]


# Section 2: Data with select composers

In [150]:
train_data = pd.read_csv(train_file)
dev_data = pd.read_csv(dev_file)
labels = ["bach", "beethoven", "brahms", "chopin", "debussy", "handel", "haydn", "liszt", "mozart", "vivaldi"]

In [151]:
train_data = train_data[train_data.y != 2] # Brahms
train_data = train_data[train_data.y != 4] # Debussy
train_data = train_data[train_data.y != 6] # Haydn
train_data = train_data[train_data.y != 7] # Liszt
train_data = train_data[train_data.y != 9] # Vivaldi

dev_data = dev_data[dev_data.y != 2] # Brahms
dev_data = dev_data[dev_data.y != 4] # Debussy
dev_data = dev_data[dev_data.y != 6] # Haydn
dev_data = dev_data[dev_data.y != 7] # Liszt
dev_data = dev_data[dev_data.y != 9] # Vivaldi

In [152]:
train_y = train_data[['y']]
train_X = train_data.drop(['y', 'Note_Density_per_Quarter_Note_Variability'], axis=1)
dev_y = dev_data[['y']]
dev_X = dev_data.drop(['y', 'Note_Density_per_Quarter_Note_Variability'], axis=1)

# Composer Experimentation: Softmax

In [153]:
# Softmax
clf = LogisticRegression(multi_class='multinomial', solver='lbfgs', penalty='l2').fit(train_X, train_y)

//anaconda/lib/python3.5/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [154]:
# Training data
y_pred = clf.predict(train_X)
confusion_m = confusion_matrix(train_y, y_pred, labels=[0, 1, 3, 5, 8])
training_accuracy = clf.score(train_X, train_y)
print(training_accuracy)
print(confusion_m)

0.8962158111652304
[[826  25   1   0   0]
 [ 37 376  21  22   0]
 [  0  34 141  36   0]
 [  0   4  14 329  70]
 [  0   0   3  10 720]]


In [155]:
# Dev data
y_pred = clf.predict(dev_X)
confusion_m = confusion_matrix(dev_y, y_pred, labels=[0, 1, 3, 5, 8])
dev_accuracy = clf.score(dev_X, dev_y)
print(dev_accuracy)
print(confusion_m)

0.871331828442438
[[284   6   0   1   0]
 [ 17 127  10   8   0]
 [  0  15  34   9   0]
 [  0   2   6  70  33]
 [  0   0   0   7 257]]


# Composer Experimentation: SVM, C=1

In [156]:
clf = SVC(gamma = 'auto', kernel='rbf', C=1)
clf.fit(train_X, train_y)

//anaconda/lib/python3.5/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [157]:
# Training data
y_pred = clf.predict(train_X)
confusion_m = confusion_matrix(train_y, y_pred, labels=[0, 1, 3, 5, 8])
training_accuracy = clf.score(train_X, train_y)
print(training_accuracy)
print(confusion_m)

1.0
[[852   0   0   0   0]
 [  0 456   0   0   0]
 [  0   0 211   0   0]
 [  0   0   0 417   0]
 [  0   0   0   0 733]]


In [158]:
# Dev data
y_pred = clf.predict(dev_X)
confusion_m = confusion_matrix(dev_y, y_pred, labels=[0, 1, 3, 5, 8])
dev_accuracy = clf.score(dev_X, dev_y)
print(dev_accuracy)
print(confusion_m)

0.3329571106094808
[[291   0   0   0   0]
 [162   0   0   0   0]
 [ 58   0   0   0   0]
 [111   0   0   0   0]
 [260   0   0   0   4]]


# Composer Experimentation: SVM, Kernel = Linear

In [159]:
clf = SVC(gamma = 'auto', kernel='linear', C=1)
clf.fit(train_X, train_y)

//anaconda/lib/python3.5/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [160]:
# Training data
y_pred = clf.predict(train_X)
confusion_m = confusion_matrix(train_y, y_pred, labels=[0, 1, 3, 5, 8])
training_accuracy = clf.score(train_X, train_y)
print(training_accuracy)
print(confusion_m)

1.0
[[852   0   0   0   0]
 [  0 456   0   0   0]
 [  0   0 211   0   0]
 [  0   0   0 417   0]
 [  0   0   0   0 733]]


In [161]:
# Dev data
y_pred = clf.predict(dev_X)
confusion_m = confusion_matrix(dev_y, y_pred, labels=[0, 1, 3, 5, 8])
dev_accuracy = clf.score(dev_X, dev_y)
print(dev_accuracy)
print(confusion_m)

1.0
[[291   0   0   0   0]
 [  0 162   0   0   0]
 [  0   0  58   0   0]
 [  0   0   0 111   0]
 [  0   0   0   0 264]]
